apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-08-25T05:13:47Z"
  generation: 1
  labels:
    app: redis-dpl
  name: redis-dpl
  namespace: default
  resourceVersion: "213864"
  uid: 67c3138b-ed0c-46dd-89d3-8990fdf1fc41
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-dpl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-dpl
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
