apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-srv
  name: nginx-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-srv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-srv
    spec:
      containers:
      - image: iamjahid/online-shop:37
        name: nginx
        resources: {}
status: {}
