apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website-com-bd
  name: website-com-bd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-com-bd
  strategy: {}
  template:
    metadata:
      labels:
        app: website-com-bd
    spec:
      containers:
      - image: iamjahid/ngnixweb:33
        name: nginx

