apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: website-com-bd
  name: website-com-bd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website-com-bd
  type: NodePort
status:
  loadBalancer: {}

