apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: e-web
  name: e-web-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: e-web
  type: LoadBalancer
status:
  loadBalancer: {}
