apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-08-25T05:16:05Z"
  generation: 1
  labels:
    app: redis-srv
  name: redis-srv
  namespace: default
  resourceVersion: "214075"
  uid: e854b9ce-8304-4bd9-8036-c13ffc957009
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-srv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-srv
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
